from __future__ import annotations

from enum import StrEnum


class ClaimStatus(StrEnum):
    PROPOSED = "PROPOSED"
    HEURISTIC = "HEURISTIC"
    EMPIRICALLY_OBSERVED = "EMPIRICALLY_OBSERVED"
    SOURCE_REPORTED = "SOURCE_REPORTED"
    CANDIDATE_LEMMA = "CANDIDATE_LEMMA"
    AGENT_AUDITED_LOCAL = "AGENT_AUDITED_LOCAL"
    AGENT_AUDITED_GLOBAL = "AGENT_AUDITED_GLOBAL"
    CHALLENGED = "CHALLENGED"
    REFUTED = "REFUTED"
    CONDITIONAL = "CONDITIONAL"
    HUMAN_CHECKED = "HUMAN_CHECKED"
    FORMALLY_CERTIFIED = "FORMALLY_CERTIFIED"
    REVOKED = "REVOKED"


class RouteMode(StrEnum):
    DEDUCTIVE = "DEDUCTIVE"
    REFUTATIONAL = "REFUTATIONAL"
    CONCEPTUAL = "CONCEPTUAL"
    EMPIRICAL = "EMPIRICAL"
    SOURCE_AUDIT = "SOURCE_AUDIT"


class RouteStatus(StrEnum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    METHOD_FAILED = "METHOD_FAILED"
    REFUTED = "REFUTED"
    SUBSUMED = "SUBSUMED"
    OBSOLETE = "OBSOLETE"
    PARKED = "PARKED"
    NEEDS_REPRESENTATION_CHANGE = "NEEDS_REPRESENTATION_CHANGE"
    NEEDS_HUMAN_IDEA = "NEEDS_HUMAN_IDEA"
    EARLY_STOPPED_KNOWN_ROUTE = "EARLY_STOPPED_KNOWN_ROUTE"
    COMPLETE_CANDIDATE = "COMPLETE_CANDIDATE"


class FailureClass(StrEnum):
    FALSE_PROPOSITION = "FALSE_PROPOSITION"
    MISSING_HYPOTHESIS = "MISSING_HYPOTHESIS"
    STATEMENT_DRIFT = "STATEMENT_DRIFT"
    CIRCULAR_REDUCTION = "CIRCULAR_REDUCTION"
    NONUNIFORM_CONSTANT = "NONUNIFORM_CONSTANT"
    ENDPOINT_FAILURE = "ENDPOINT_FAILURE"
    LOSS_INTRINSIC_TO_METHOD = "LOSS_INTRINSIC_TO_METHOD"
    REPRESENTATION_TOO_WEAK = "REPRESENTATION_TOO_WEAK"
    SOURCE_MISMATCH = "SOURCE_MISMATCH"
    INTERFACE_MISMATCH = "INTERFACE_MISMATCH"
    VERIFIER_UNCERTAINTY = "VERIFIER_UNCERTAINTY"
    EXPOSITION_ONLY = "EXPOSITION_ONLY"
    COMPUTATION_INCONCLUSIVE = "COMPUTATION_INCONCLUSIVE"
    RESOURCE_EXHAUSTION = "RESOURCE_EXHAUSTION"
    REPEATED_NO_NEW_INFORMATION = "REPEATED_NO_NEW_INFORMATION"


class EvidenceType(StrEnum):
    DEDUCTIVE_PROOF = "DEDUCTIVE_PROOF"
    EXACT_COUNTEREXAMPLE = "EXACT_COUNTEREXAMPLE"
    EXHAUSTIVE_FINITE_SEARCH = "EXHAUSTIVE_FINITE_SEARCH"
    INTERVAL_CERTIFICATE = "INTERVAL_CERTIFICATE"
    FLOATING_POINT_EXPERIMENT = "FLOATING_POINT_EXPERIMENT"
    SYMBOLIC_CERTIFICATE = "SYMBOLIC_CERTIFICATE"
    LITERATURE_THEOREM = "LITERATURE_THEOREM"
    ANALOGY = "ANALOGY"
    LLM_AUDIT = "LLM_AUDIT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    LEAN_PROOF = "LEAN_PROOF"


class AuditVerdict(StrEnum):
    PASS = "PASS"
    REJECT = "REJECT"
    UNCERTAIN = "UNCERTAIN"
    NEEDS_SOURCE_AUDIT = "NEEDS_SOURCE_AUDIT"
    NEEDS_HUMAN = "NEEDS_HUMAN"


class InterventionDecision(StrEnum):
    ACCEPT_STOP = "ACCEPT_STOP"
    REJECT_DIFFERENT_ROUTE = "REJECT_DIFFERENT_ROUTE"
    REJECT_NOT_APPLICABLE = "REJECT_NOT_APPLICABLE"
    NEED_HUMAN_REVIEW = "NEED_HUMAN_REVIEW"


class InterventionKind(StrEnum):
    KNOWN_ROUTE = "KNOWN_ROUTE"
    KNOWN_DEAD_END = "KNOWN_DEAD_END"
    EXACT_RESULT_KNOWN = "EXACT_RESULT_KNOWN"
    SOURCE_MISMATCH = "SOURCE_MISMATCH"
    DIFFERENCE_CONFIRMED = "DIFFERENCE_CONFIRMED"
    NO_INTERVENTION = "NO_INTERVENTION"


class CampaignStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    PAUSED_HUMAN = "PAUSED_HUMAN"
    CONTRACT_CHANGED = "CONTRACT_CHANGED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    COMPLETED_UNSOLVED = "COMPLETED_UNSOLVED"
    COMPLETE_PROOF_CANDIDATE = "COMPLETE_PROOF_CANDIDATE"
    REFUTATION_CANDIDATE = "REFUTATION_CANDIDATE"
    HUMAN_CHECKED = "HUMAN_CHECKED"
    FORMALLY_CERTIFIED = "FORMALLY_CERTIFIED"
